name:                dependent-hashmap
version:             0.1.0.1
synopsis:            Dependent hash maps
description:         Provides @DHashMap@, a type for hash maps where the keys can specify the type of value that is associated with them.
homepage:            https://github.com/ollef/dependent-hashmap#readme
license:             BSD3
author:              Olle Fredriksson
maintainer:          fredriksson.olle@gmail.com
copyright:           2020 Olle Fredriksson
category:            Data
extra-source-files:
- README.md
tested-with:         GHC == 8.0.2, GHC == 8.2.2, GHC == 8.4.3, GHC == 8.6.5, GHC == 8.8.3

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wtabs

dependencies:
  - base >= 4.7 && < 5
  - constraints-extras >= 0.3
  - dependent-sum >= 0.6
  - hashable >= 1.3
  - unordered-containers >= 0.2.9

library:
  source-dirs: src

tests:
  test-dependent-hashmap:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - constraints
      - dependent-hashmap
      - hedgehog
      - mtl
      - some >= 1.0.6 && <= 1.1
